package rules.simple

import pl.edu.atar.universityrecruitment.Candidate;

// Kwalifikacja olimpijska
rule "Olympic qualification (two_sets_of_rules_salience_activation-group)"
dialect "java"
agenda-group "two_sets_of_rules_salience_activation-group"
salience 200
activation-group "group-1"
when
    $uc : Candidate(olympicFinalist == true)
then
    $uc.setAdmission(true);
    $uc.setQualificationType("Olympic qualification");
    $uc.appendLogger("Agenda 'TWO_SETS_OF_RULES_SALIENCE_ACTIVATION_GROUP' got focus!");
    $uc.appendLogger("Rule 'Olympic qualification' fired!");
end