package rules.elementary

import pl.edu.atar.universityrecruitment.Candidate;

// Kwalifikacja olimpijska
rule "Olympic Qualification (main)"
dialect "java"
// Reguły bez przypisanej agenda-group są przyporządkowane do domyślnej agendy 'MAIN'!
// Agenda 'MAIN' jest w procesie wnioskowanie ZAWSZE wywoływana tj. uzyskuje FOCUS.
// Wywołanie jest niejawne i odbywa się po jawnych wywołaniach agend.
// Aby wyłączyć automatyczne uruchamianie n/w reguły należy ją przypisać do agendy z wykorzystaniem atrybutu agenda-group.

when
    $uc : Candidate(olympicFinalist == true)
then
    $uc.setAdmission(true);
    $uc.setQualificationType("Olympic qualification");
    $uc.appendLogger("Agenda 'MAIN' got focus!");
    $uc.appendLogger("Rule 'Olympic qualification' fired!");
end