package rules.elementary

import pl.edu.atar.universityrecruitment.Candidate;

// Informatyka
rule "Exam Qualification / Informatyka (one_set_of_rules_no-loop_MODIFY)"
dialect "java"
agenda-group "one_set_of_rules_no-loop_MODIFY"
no-loop true
when
    $uc : Candidate(examResult > 100, fieldOfStudy == "Informatyka", counter < 10)
then
  	modify($uc) { 
		setAdmission(Boolean.TRUE),
    	setQualificationType("Exam qualification"),
    	appendLogger("Rule 'Exam qualification / Informatyka' fired!"),
		incrementCounter()
    }    
end

// Automatyka i robotyka
rule "Exam Qualification / Automatyka i robotyka (one_set_of_rules_no-loop_MODIFY)"
dialect "java"
agenda-group "one_set_of_rules_no-loop_MODIFY"
no-loop true
when
    $uc : Candidate(examResult > 60, fieldOfStudy == "Automatyka i robotyka", counter < 10)
then
  	modify($uc) { 
		setAdmission(Boolean.TRUE),
    	setQualificationType("Exam qualification"),
    	appendLogger("Rule 'Exam qualification / Automatyka i robotyka' fired!"),
		incrementCounter()
    }    
end

// Elektrotechnika
rule "Exam Qualification / Elektrotechnika (one_set_of_rules_no-loop_MODIFY)"
dialect "java"
agenda-group "one_set_of_rules_no-loop_MODIFY"
no-loop true
when
    $uc : Candidate(examResult > 80, fieldOfStudy == "Elektrotechnika", counter < 10)
then
  	modify($uc) { 
		setAdmission(Boolean.TRUE),
    	setQualificationType("Exam qualification"),
    	appendLogger("Rule 'Exam qualification / Elektrotechnika' fired!"),
		incrementCounter()
    }    
    
end