package rules.knowledgeable

import pl.edu.atar.universityrecruitment.Candidate;

// Kwalifikacja kobiet
rule "Women qualification (three_sets_of_rules_salience_lock-on-active_bonus_MODIFY)"
dialect "java"
agenda-group "three_sets_of_rules_salience_lock-on-active_bonus_MODIFY"
salience 200
lock-on-active true

when
    $uc : Candidate(schoolType == "Technical")
then
  	modify($uc) {
        setExamResult($uc.getExamResult() + 25),
    	appendLogger("Rule 'Technical school bonus' fired!")
    }
end