package rules.expert.noobligatory

import pl.edu.atar.universityrecruitment.Candidate;

// Informatyka
rule "Exam Qualification / Informatyka (exam_result_calculation)"
dialect "java"
agenda-group "exam_result_calculation"
activation-group "group-qualification"
salience 100

when
    $uc : Candidate(fieldOfStudy == "Informatyka", examResult >= 200.0)
then
  	$uc.appendLogger("Total candidate exam result = " + $uc.getExamResult());	
	$uc.setAdmission(true);
    $uc.setQualificationType("Exam qualification");
    $uc.appendLogger("Rule 'Exam qualification / Informatyka' fired!");
end


// Automatyka i robotyka
rule "Exam Qualification / Automatyka i robotyka (exam_result_calculation)"
dialect "java"
agenda-group "exam_result_calculation"
salience 100
activation-group "group-qualification"

when
    $uc : Candidate(fieldOfStudy == "Automatyka i robotyka", examResult >= 130.0)
then
 	$uc.appendLogger("Total candidate exam result = " + $uc.getExamResult());
	$uc.setAdmission(true);
   	$uc.setQualificationType("Exam qualification");
   	$uc.appendLogger("Rule 'Exam qualification / Automatyka i robotyka' fired!");
end


// Elektrotechnika
rule "Exam Qualification / Elektrotechnika (exam_result_calculation)"
dialect "java"
agenda-group "exam_result_calculation"
salience 250
activation-group "group-qualification"

when
    $uc : Candidate(fieldOfStudy == "Elektrotechnika", examResult >= 80.0)
then
 	$uc.appendLogger("Total candidate exam result = " + $uc.getExamResult() + ". Minimum required exam result 80.0D");
	$uc.setAdmission(true);
   	$uc.setQualificationType("Exam qualification");
   	$uc.appendLogger("Rule 'Exam qualification / Elektrotechnika' fired!");
end


// Pielęgniarstwo
rule "Exam Qualification / Pielęgniarstwo (exam_result_calculation)"
dialect "java"
agenda-group "exam_result_calculation"
salience 250
activation-group "group-qualification"

when
    $uc : Candidate(fieldOfStudy == "Pielęgniarstwo", examResult >= 180.0)
then
 	$uc.appendLogger("Total candidate exam result = " + $uc.getExamResult() + ". Minimum required exam result 180.0D");
	$uc.setAdmission(true);
   	$uc.setQualificationType("Exam qualification");
   	$uc.appendLogger("Rule 'Exam qualification / Pielęgniarstwo' fired!");
end


// Psychologia
rule "Exam Qualification / Psychologia (exam_result_calculation)"
dialect "java"
agenda-group "exam_result_calculation"
salience 250
activation-group "group-qualification"

when
    $uc : Candidate(fieldOfStudy == "Psychologia", examResult >= 150.0)
then
 	$uc.appendLogger("Total candidate exam result = " + $uc.getExamResult() + ". Minimum required exam result 150.0D");
	$uc.setAdmission(true);
   	$uc.setQualificationType("Exam qualification");
   	$uc.appendLogger("Rule 'Exam qualification / Psychologia' fired!");
end