package rules.virtuoso.noobligatory

import pl.edu.atar.universityrecruitment.Candidate;
import pl.edu.atar.universityrecruitment.ExamSubjectResult;

// Kwalifikacja na podstawie egzaminu : Sumowanie wyniku przedmiotu egzaminacyjnego

// Informatyka
rule "Subject result summation / Informatyka (exam_result_calculation)"
dialect "java"
agenda-group "exam_result_calculation"
salience 400

when
    $uc : Candidate(fieldOfStudy == 'Informatyka')
    $esr : ExamSubjectResult(examSubject in ('matematyka', 'informatyka'))
then
	modify($uc) {
    	appendLogger("Rule 'Subject result summation (exam_result_calculation)' fired! Exam result = "
    	 			 + $uc.getExamResult() + " + " + $esr.getExamResult() + " (" + $esr.getExamSubject() + ")"),  	
  		setExamResult($uc.getExamResult() + $esr.getExamResult())
    }	
  	retract($esr);
end

// Automatyka i robotyka
rule "Subject result summation / Automatyka i robotyka (exam_result_calculation)"
dialect "java"
agenda-group "exam_result_calculation"
salience 400

when
    $uc : Candidate(fieldOfStudy == 'Automatyka i robotyka')
    $esr : ExamSubjectResult(examSubject in ('matematyka'))
then
	modify($uc) {
    	appendLogger("Rule 'Subject result summation (exam_result_calculation)' fired! Exam result = "
    	 			 + $uc.getExamResult() + " + " + $esr.getExamResult() + " (" + $esr.getExamSubject() + ")"),  	
  		setExamResult($uc.getExamResult() + $esr.getExamResult())
    }	
  	retract($esr);
end

// Elektrotechnika
rule "Subject result summation / Elektrotechnika (exam_result_calculation)"
dialect "java"
agenda-group "exam_result_calculation"
salience 400

when
    $uc : Candidate(fieldOfStudy == 'Elektrotechnika')
    $esr : ExamSubjectResult(examSubject in ('matematyka', 'fizyka'))
then
	modify($uc) {
    	appendLogger("Rule 'Subject result summation (exam_result_calculation)' fired! Exam result = "
    	 			 + $uc.getExamResult() + " + " + $esr.getExamResult() + " (" + $esr.getExamSubject() + ")"),  	
  		setExamResult($uc.getExamResult() + $esr.getExamResult())
    }
  	retract($esr);
end

// Pielęgniarstwo
rule "Subject result summation / Pielęgniarstwo (exam_result_calculation)"
dialect "java"
agenda-group "exam_result_calculation"
salience 400

when
    $uc : Candidate(fieldOfStudy == 'Pielęgniarstwo')
    $esr : ExamSubjectResult(examSubject in ('chemia', 'biologia'))
then
	modify($uc) {
    	appendLogger("Rule 'Subject result summation (exam_result_calculation)' fired! Exam result = "
    	 			 + $uc.getExamResult() + " + " + $esr.getExamResult() + " (" + $esr.getExamSubject() + ")"),  	
  		setExamResult($uc.getExamResult() + $esr.getExamResult())
    }
  	retract($esr);
end

// Psychologia
rule "Subject result summation / Psychologia (exam_result_calculation)"
dialect "java"
agenda-group "exam_result_calculation"
salience 400

when
    $uc : Candidate(fieldOfStudy == 'Psychologia')
    $esr : ExamSubjectResult(examSubject in ('język polski'))
then
	modify($uc) {
    	appendLogger("Rule 'Subject result summation (exam_result_calculation)' fired! Exam result = "
    	 			 + $uc.getExamResult() + " + " + $esr.getExamResult() + " (" + $esr.getExamSubject() + ")"),  	
  		setExamResult($uc.getExamResult() + $esr.getExamResult())
    }
  	retract($esr);
end